### ISSUE TITLE
Getting a website up and running

### ISSUE THREAD

**Issue by smac89** [UofSSpaceDesignTeam/gui-software#1]
I am not very well versed with servers and as such I am still reading up on how to use [Bottle](http://bottlepy.org/docs/dev/index.html). But this doesn't mean we can't host the website yet.
Github has this nice feature called [github pages](https://pages.github.com/) which is very easy to setup ([Checkout](http://smac89.github.io/gui-software/) this demo I just made). Make sure you first <kbd>Fork</kbd> the project to your repo, then continue with the tutorial.

For Github to do this for you it, the automated method described will create a seperate branch called **gh-pages** which is where all the code for the website will live. All you have to do is move your own files into the branch and overwrite the ones that are automatically created by the tool or merge your changes if you don't want to loose the layout created. This branch does not need to be merged with the master (for obvious reasons).

And there you have it. Now you have an actual site that you can easily edit on the go and see your changes in realtime. This will do for now until I have time to learn more about Bottle or someone else takes care of that part

**Comment by ausshir** [comment]
This is actually to serve up a GUI from our rover, so the GitHub pages isn’t particularly useful at this time. Setting up a local test webserver isn’t a problem for Liam (who is developing the pages), but developing something that interfaces with the Python framework we already have is the key – that’s where Bottle comes into play!

There’s also some alternatives called Flask, Django and Twisted that do something similar and I’m not dead set on Bottle if it looks too complicated to set up! The reason I was interested in it is we have a very small embedded computer on the rover (Intel Edison), so we wanted a webserver that operated as simply as possible in order to keep everything running smoothly.

Also keep in mind that the server does not have to be on the internet – just locally from one computer to another on something like a LAN.

No worries if you are getting stuck with the python stuff, we can totally chat about it on Thursday or whenever you next come in! (Also thanks for using the issues tracker) :D

Austin Shirley

**Comment by ottopasuuna** [comment]
I'd say this is done. 😉
